### ISSUE TITLE
Line of sight update on drop not updating

### ISSUE THREAD

**Issue by ep1cman** [encounterplus/web-client#1]
There is a slight issue when line of sight is set to update on drop. It wont actually update in the web view unless the token is clicked a second time

**Comment by jurex** [comment]
thanks for the issue @ep1cman,  I still need to figure out how to do this properly, because right now, los is calculated directly on ipad/iphone, so there is a slight delay between los update and data sync.

**Comment by jurex** [comment]
fixed by using new lineOfSightUpdateEvent here:
20c072c38f23d41e66f1c21b3f7949b13d968d23
