### ISSUE TITLE
[Bug] Player character movement disrupted by DM map movement.

### ISSUE THREAD

**Issue by Splinter714** [encounterplus/web-client#18]
When a player attempts to move their character while the DM is moving or zooming the map in the app, the player is unable to accurately move their character as desired.

**Comment by Duseylicious** [comment]
I came here to post this. :) Recorded a video if it helps diagnose. https://drive.google.com/file/d/1azN7tQ-gLPwdMoMeqg_YSTLUjtHT2tKg/view?usp=sharing

**Comment by jurex** [comment]
fixed
