### ISSUE TITLE
Text chat

### ISSUE THREAD

**Issue by Rycochet** [encounterplus/web-client#28]
This is relatively simple to add in the client, but would also need display in the App.

Just a simple text chat for people, require people to not be `Unknown` for it. Option in the App to allow for spectators (non-Unknown still).

Allow very basic bold / italic / underline modifiers as standard  in other text chats.

Links should be auto-linked with text-overflow on the length, and `target="_blank"` to ensure a new tab.

Potential questions:

* Rate limiting?
* Mute people?
* Inline dice roller?

**Comment by jurex** [comment]
done
