### ISSUE TITLE
[Feature Request] Show names of PCs on web view

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/web-client#44]
My players often glance at the screen to see everyone's names. It really helps everyone remember our PC's names, or if we forget them, at least be able to look at them and use it. :)  I'd be happy with just 1.) but though 2.) could be cool also.

1.) Show full name of PCs & friendlies (not enemies) during initiative on the web view.  (It already does this on the second screen.)

2.) It'd be cool to have an option that shows the PC names / portraits on the second screen / web view even when not in combat.  Could be an option in the settings.

**Comment by jurex** [comment]
fixed
