### ISSUE TITLE
[Bug?] Crop webview portraits on web view initiative tracker

### ISSUE THREAD

**Issue by Duseylicious** [encounterplus/web-client#45]
Some portraits (the ones that show up during combat) in the web view don't "fill" properly and leave a gap at the bottom.  Attached image showing what I mean.

Thanks!
![Screen Shot 2020-06-06 at 11 38 20 AM](https://user-images.githubusercontent.com/63576494/83952852-cbb75200-a7f0-11ea-9827-604335f06e8b.png)

**Comment by jurex** [comment]
lol, that image :D :D

**Comment by Duseylicious** [comment]
😂

**Comment by jurex** [comment]
fixed
