### ISSUE TITLE
DM layer visible

### ISSUE THREAD

**Issue by rrgeorge** [encounterplus/web-client#8]
The DM Layer is visible on the web client.

**Comment by ep1cman** [comment]
![image](https://user-images.githubusercontent.com/5303409/82661757-7f7ee600-9c24-11ea-8336-05e08d205059.png)
Seems to work fine on my end

**Comment by Rycochet** [comment]
From discord:

> To add: Anything written with the pen or highlighter on the DM layer are visible to players using the remote web client.
> Markers and tiles added on the DM layer are invisible

**Comment by rrgeorge** [comment]
I had tiles show up.

>

**Comment by jurex** [comment]
fixed
